package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* domingo 20 de marzo de 2022 19H25' CET
*/

public interface HelloOperations 
{
  String sayHello ();
  String Mayus (String a);
  String Minus (String a);
  String ContarPalabras (String a);
  String PalabraLarga (String a);
  void shutdown ();
} // interface HelloOperations
